<a href="https://colab.research.google.com/github/Jomapime/Manejo_de_datos_en_Python/blob/main/Primera_clase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tipos de datos


In [ ]:
print(type(5))#Entero - int
print(type(10.5)) #decimal - float o dbl
print(type("Hola mundo")) #String
print(type(2+3j)) #Complex
print(type(True)) #Booleano - Logico


<class 'int'>
<class 'float'>
<class 'str'>
<class 'complex'>
<class 'bool'>


# Operaciones matemáticas básicas.

In [ ]:
#Suma
print(1+2)
#Resta
print(10-5)
#multiplicacion
print(5*4)
#potencia
print(8**2)
pow(8,3)
#Division
print(8/5)
#Division entera
print(25//3)

3
5
20
64
1.6
8


# Estructuras de datos

## Variables

In [ ]:
Variable1 = 105
Variable2 = 650

Suma = Variable1+Variable2
print(Suma)

print("La suma de", Variable1, "+", Variable2, "=", Suma)

755


# Ejercicio



Ejercicio: 

Cual es el valor presente del siguiente flujo de ingresos con factor de descuento del 12%?
Recibirá 60.000 COP en un año, 100.000 COP en dos años y 200.000 COP en tres años.
 
FORMULA:

**$$
VP = \frac{VF}{(1+i)^n}
$$**

**$$
VP = VF/(1+i)^n
$$**

Cree un objeto para cada valor presente (son 3), luego cree otro objeto que sea el resultado de la suma de los 3 valores presentes.

In [ ]:
VP1 = 60000/(1+0.12)**1
VP2 = 100000/(1+0.12)**2
VP3 = 200000/(1+0.12)**3


In [ ]:
print(VP1)
print(VP2)
print(VP3)

53571.428571428565
79719.38775510203
142356.04956268216


In [ ]:
Resultado = VP1+VP2+VP3
print(Resultado)
Resultado = round(Resultado,3)
print(Resultado)

275646.86588921276
275646.866


In [ ]:
Resultado

275646.866

# Vectores



Secuencia u objeto unidimensional


$ Vector1 = (1,2,3,4,5,6) $

$ Vector2 = (arbol, casa, persona)$

In [ ]:
import numpy as np
# Para secuencias numericas
np.arange(6)
print(np.arange(-3,6)) #Numero de inicio, numero final (El ultimo valor no se incluye)

print(np.arange(0,22,2)) #Numero de inicio, numero final, saltos


[-3 -2 -1  0  1  2  3  4  5]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
Secuencia = np.linspace(5,7,15, endpoint=True) #Numero inicial, numero final, cantidad de numeros, incluir el ultimo valor.
np.linspace(5,7,15, endpoint=False) #Numero inicial, numero final, cantidad de numeros, no incluye el ultimo valor.
print(Secuencia)
print(np.round(Secuencia,2))

[5.         5.14285714 5.28571429 5.42857143 5.57142857 5.71428571
 5.85714286 6.         6.14285714 6.28571429 6.42857143 6.57142857
 6.71428571 6.85714286 7.        ]
[5.   5.14 5.29 5.43 5.57 5.71 5.86 6.   6.14 6.29 6.43 6.57 6.71 6.86
 7.  ]


In [ ]:
Secuencia[0] #Mirar el primer valor.
Secuencia[2] #Mirar el tercer valor.
Secuencia[1] = 200 #Cambiar el segundo valor.
Secuencia[4] = 620 #Cambiar el quinto valor.
print(Secuencia) 

[  5.         200.           5.28571429   5.42857143 620.
   5.71428571   5.85714286   6.           6.14285714   6.28571429
   6.42857143   6.57142857   6.71428571   6.85714286   7.        ]


# Ejercicio 2

**Ejercicio:** 
1. Crear un vector que vaya desde -5 hasta 6 y que tenga 7 numeros. **linspace**
2. Construya una secuencia numérica que inicie en 20 y termine en 50, dando saltos de 5 en 5. **arange**

## Operaciones con vectores.

In [ ]:
import numpy as np

In [ ]:
Vector1 = np.array([4,3,6,7]) #Creacion de vector.
Vector2 = np.array([5,4,3,2])
print(Vector1)
print(Vector2)

[4 3 6 7]
[5 4 3 2]


In [ ]:
print(Vector1+Vector2) #Suma de dos vectores
print(Vector1**Vector2) #Multiplicacion de dos vectores.


[9 7 9 9]
[1024   81  216   49]


In [ ]:
print(np.sum(Vector1)) #Suma elementos del vector.
print(np.log(Vector1)) #Logaritmo natural de los elementos del vector.
print(np.max(Vector1)) #Numero maximo del vector.
print(np.min(Vector1)) #Numero minimo del vector.

20
[1.38629436 1.09861229 1.79175947 1.94591015]
7
3


# Matrices.



Una matriz es un arreglo bidimensional de números. 

$$\mathbf{X} = \left[\begin{array}
{rrr}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 
\end{array}\right]$$

# Ejercicio 3


**Ejercicio:**
1. Cree las siguientes matrices.

$$\mathbf{A} = \left[\begin{array}
{rrr}
1 & 4 \\
2 & 5 \\
3 & 6
\end{array}\right]$$


$$\mathbf{B} = \left[\begin{array}
{rrr}
1 & 2 \\
3 & 4 \\
5 & 6
\end{array}\right]$$

2. Multiplique las dos matrices.